### ISSUE TITLE
Change Color Scheme

### ISSUE THREAD

**Issue by SardulDhyani** [SardulDhyani/Github-Finder#1]
Change color Scheme of the app.

**Comment by muhammadawaisshaikh** [comment]
what colour you want to change comment the hash colour code.

**Comment by SardulDhyani** [comment]
Hi, @muhammadawaisshaikh 
I have used bootswatch in the app, I was thinking of something like changing the current ui to dark theme based ui.

**Comment by muhammadawaisshaikh** [comment]
ok got your point, we should have to use the toggle of the dark and light version. is it ok for the requirements?

**Comment by SardulDhyani** [comment]
@muhammadawaisshaikh yes you can also create new toggle or only dark theme will also work. 
You can do whatever you want 🙂

**Comment by muhammadawaisshaikh** [comment]
thanks, man. will give you the PR as it has done. I am taking this issue 💯

**Comment by SardulDhyani** [comment]
ok, @muhammadawaisshaikh I am assigning this to you.

Happy Contributing 🙂🙂

**Comment by muhammadawaisshaikh** [comment]
it's **_done_**. I have created the **Pull Request**.

**Comment by muhammadawaisshaikh** [comment]
can you please add this label in your repo "**hacktoberfest**" 
you have added "**Hacktoberfest**" through which your repo is showing as Ineligible Repository in my hacktoberfest profile.

thanks.

**Comment by SardulDhyani** [comment]
Ok, @muhammadawaisshaikh I'll get back to you after checking your Pr😃

**Comment by muhammadawaisshaikh** [comment]
close the issue to avoid inconvenience. thanks
